apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    common.k8s.elastic.co/template-hash: "705845254"
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  name: quickstart-kb
  ownerReferences:
  - apiVersion: kibana.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Kibana
    name: quickstart
    uid: 4fa79bcb-5eb5-4c07-8470-6f56a777c4fd
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/quickstart-kb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
      kibana.k8s.elastic.co/name: quickstart
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        common.k8s.elastic.co/type: kibana
        kibana.k8s.elastic.co/config-checksum: 7eb825db9d5e7ad4ff9f58f7e913d0138a6998d6f00ed154413edadf
        kibana.k8s.elastic.co/name: quickstart
        kibana.k8s.elastic.co/version: 7.6.2
    spec:
      automountServiceAccountToken: false
      containers:
      - image: docker.elastic.co/kibana/kibana:7.6.2
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 5601
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/kibana/data
          name: kibana-data
        - mountPath: /usr/share/kibana/config
          name: config
          readOnly: true
        - mountPath: /usr/share/kibana/config/elasticsearch-certs
          name: elasticsearch-certs
          readOnly: true
        - mountPath: /mnt/elastic-internal/http-certs
          name: elastic-internal-http-certificates
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: kibana-data
      - name: config
        secret:
          defaultMode: 420
          optional: false
          secretName: quickstart-kb-config
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: quickstart-kb-es-ca
      - name: elastic-internal-http-certificates
        secret:
          defaultMode: 420
          optional: false
          secretName: quickstart-kb-http-certs-internal
status: {}
