apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: praeco
    meta.helm.sh/release-namespace: default
  creationTimestamp: null
  generation: 1
  labels:
    app.kubernetes.io/instance: praeco
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: praeco
    app.kubernetes.io/version: 1.0.1
    helm.sh/chart: praeco-0.1.2
  name: praeco
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/praeco
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: praeco
      app.kubernetes.io/name: praeco
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: praeco
        app.kubernetes.io/name: praeco
    spec:
      containers:
      - image: servercentral/praeco:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: praeco
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: default-conf
          subPath: default.conf
        - mountPath: /var/www/html/praeco.config.json
          name: praeco-config
          subPath: praeco.config.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: nginx_config
            path: nginx.conf
          name: praeco-nginx-config
        name: nginx-conf
      - configMap:
          defaultMode: 420
          items:
          - key: nginx_config_default
            path: default.conf
          name: praeco-nginx-default-config
        name: default-conf
      - configMap:
          defaultMode: 420
          items:
          - key: praeco_config
            path: praeco.config.json
          name: praeco-config
        name: praeco-config
status: {}
