apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      kibana'
  creationTimestamp: null
  generateName: quickstart-kb-86b564fcf-
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/config-checksum: 7eb825db9d5e7ad4ff9f58f7e913d0138a6998d6f00ed154413edadf
    kibana.k8s.elastic.co/name: quickstart
    kibana.k8s.elastic.co/version: 7.6.2
    pod-template-hash: 86b564fcf
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: quickstart-kb-86b564fcf
    uid: 0f12637c-86a1-4a99-b088-28e3acf08956
  selfLink: /api/v1/namespaces/default/pods/quickstart-kb-86b564fcf-7njdn
spec:
  automountServiceAccountToken: false
  containers:
  - image: docker.elastic.co/kibana/kibana:7.6.2
    imagePullPolicy: IfNotPresent
    name: kibana
    ports:
    - containerPort: 5601
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /login
        port: 5601
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/kibana/data
      name: kibana-data
    - mountPath: /usr/share/kibana/config
      name: config
      readOnly: true
    - mountPath: /usr/share/kibana/config/elasticsearch-certs
      name: elasticsearch-certs
      readOnly: true
    - mountPath: /mnt/elastic-internal/http-certs
      name: elastic-internal-http-certificates
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-cluster-1-default-pool-725e9481-st1d
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: kibana-data
  - name: config
    secret:
      defaultMode: 420
      optional: false
      secretName: quickstart-kb-config
  - name: elasticsearch-certs
    secret:
      defaultMode: 420
      optional: false
      secretName: quickstart-kb-es-ca
  - name: elastic-internal-http-certificates
    secret:
      defaultMode: 420
      optional: false
      secretName: quickstart-kb-http-certs-internal
status:
  phase: Pending
  qosClass: Burstable
