apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      praeco'
  creationTimestamp: null
  generateName: praeco-5f5456868f-
  labels:
    app.kubernetes.io/instance: praeco
    app.kubernetes.io/name: praeco
    pod-template-hash: 5f5456868f
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: praeco-5f5456868f
    uid: af975c0b-3956-4344-968b-bb52af851601
  selfLink: /api/v1/namespaces/default/pods/praeco-5f5456868f-p5w6t
spec:
  containers:
  - image: servercentral/praeco:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: praeco
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-conf
      subPath: nginx.conf
    - mountPath: /etc/nginx/conf.d/default.conf
      name: default-conf
      subPath: default.conf
    - mountPath: /var/www/html/praeco.config.json
      name: praeco-config
      subPath: praeco.config.json
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-qqdtj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-cluster-1-default-pool-725e9481-58wg
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: nginx_config
        path: nginx.conf
      name: praeco-nginx-config
    name: nginx-conf
  - configMap:
      defaultMode: 420
      items:
      - key: nginx_config_default
        path: default.conf
      name: praeco-nginx-default-config
    name: default-conf
  - configMap:
      defaultMode: 420
      items:
      - key: praeco_config
        path: praeco.config.json
      name: praeco-config
    name: praeco-config
  - name: default-token-qqdtj
    secret:
      defaultMode: 420
      secretName: default-token-qqdtj
status:
  phase: Pending
  qosClass: Burstable
